
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://computationalmaterials.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: "UA-124603873-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Computational Materials at Berkeley"
title: "{ CM@B }"
email: "jdagdelen@berkeley.edu"
description: "Supporting the computational materials community at the University of California, Berkeley."
keywords: "berkeley, computational materials, materials science, python, Cal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 15
start-delay: 200
delete-delay: 5000
#lines: # You can add HTML Tags in the Text
#  - text: "def predict_material(application='battery'): "
#  - text: "Can an AI understand chemistry?"
#  - text: "How can we apply machine learning in our experiments?"
#  - text: "Where can I find programming resources for materials researchers?"
lines: # You can add HTML Tags in the Text
  - text: "Can an AI understand chemistry?"
  - text: "Can ML help guide experiments?"
  - text: "Is computation just for theorists?"

me-img: "/img/octohedron_new.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/icons/smashicon/leaf.png" 
    date: "Fall 2018"
    description: "Talks, workshops, social events, and more!"
  - image: "/img/icons/smashicon/beer.png"
    date: "September 7, 2018"
    description: "Materials Happy Hour. 6pm @ [Pappy's Grill & Sports Bar](https://www.google.com/maps/dir/''/pappy's+berkeley/data=!4m5!4m4!1m0!1m2!1m1!1s0x80857c2f3bca81e1:0x27a976bc098ff9f2?sa=X&ved=2ahUKEwiCxfKnspbdAhWhPH0KHQeLDw0Q9RcwC3oECAoQFQ)"
  - image: "/img/speakers/Kristin_Persson.jpg"
    date: "September 13, 2018"
    description: "CM@B Speaker Series: [Kristin Persson, The Materials Project](/events/2018/09/13/Persson.html)"
  - image: "/img/speakers/Anubhav_Jain_2.jpg"    
    date: "October 16, 2018"
    description: "CM@B Speaker Series: [Anubhav Jain,  Machine Learning and Materials Design](/events/2018/10/16/Jain.html) (290 HMMB)"
  - image: "/img/speakers/Tess_Smidt.jpg"    
    date: "October 23, 2018"
    description: "CM@B Speaker Series: [Tess Smidt, Becoming an Atomic Architect at Google](/events/2018/10/23/Smidt.html)"
  - image: "/img/speakers/Andre_Schleife.jpg"
    date: "November 8, 2018"
    description: "CM@B Speaker Series: [André Schleife, Excited Electron States](/events/2018/11/08/Schleife.html)"
  - image: "/img/speakers/Sinead_Griffin.jpg"
    date: "November 19, 2018"
    description: "CM@B Speaker Series: [Sinéad Griffin](/events/2018/11/19/Griffin.html)"
  - image: "/img/icons/smashicon/leaves.png" 
    date: "Spring 2019"
    description: "Talks, workshops, social events, and more!"
#  - image: "/img/icons/learning/png/011-communication.png"    
#    date: "August 30, 2018"
#    description: "Fall 2018 General Meeting. Location: 348 Hearst Memorial Mining Building"

# First image of the Timeline

timeline-img: "/img/icons/learning/png/042-science.png"

###########
# Contact #
###########

email: "jdagdelen@berkeley.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Computational Materials at Berkeley is a Registered Student Organization of UC Berkeley."
author_blurb_image: "/img/logo_200px.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/ComputaionalMaterials"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Events: 'timeline'
  News: 'latest-post'
  Join: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
  
plugins:
  - jekyll-sitemap
